const MAP_URL='https://raw.githubusercontent.com/geolonia/japanese-prefectures/master/map-mobile.svg';
const KEY='travel-territory-state-v3';
const PREFS=[
['01','北海道','北海道','p1'],['02','青森','東北','p1'],['03','岩手','東北','p1'],['04','宮城','東北','p1'],['05','秋田','東北','p1'],['06','山形','東北','p1'],['07','福島','東北','p1'],
['08','茨城','関東','p2'],['09','栃木','関東','p2'],['10','群馬','関東','p2'],['11','埼玉','関東','p2'],['12','千葉','関東','p2'],['13','東京','関東','p2'],['14','神奈川','関東','p2'],
['15','新潟','中部','p3'],['16','富山','中部','p3'],['17','石川','中部','p3'],['18','福井','中部','p3'],['19','山梨','中部','p3'],['20','長野','中部','p3'],['21','岐阜','中部','p3'],['22','静岡','中部','p3'],['23','愛知','中部','p3'],
['24','三重','近畿','p4'],['25','滋賀','近畿','p4'],['26','京都','近畿','p4'],['27','大阪','近畿','p4'],['28','兵庫','近畿','p4'],['29','奈良','近畿','p4'],['30','和歌山','近畿','p4'],
['31','鳥取','中国','p1'],['32','島根','中国','p1'],['33','岡山','中国','p1'],['34','広島','中国','p1'],['35','山口','中国','p1'],
['36','徳島','四国','p2'],['37','香川','四国','p2'],['38','愛媛','四国','p2'],['39','高知','四国','p2'],
['40','福岡','九州・沖縄','p3'],['41','佐賀','九州・沖縄','p3'],['42','長崎','九州・沖縄','p3'],['43','熊本','九州・沖縄','p3'],['44','大分','九州・沖縄','p3'],['45','宮崎','九州・沖縄','p3'],['46','鹿児島','九州・沖縄','p3'],['47','沖縄','九州・沖縄','p3']];
const PREF=Object.fromEntries(PREFS.map(p=>[p[0],{code:p[0],name:p[1],region:p[2]}]));
const COLORS={p1:'#e85d63',p2:'#3e8dde',p3:'#43ad70',p4:'#e8ab2f'};
const DEFAULT={game:{started:false,startDate:'',period:1,residencePoints:5,otherPoints:10},players:[{id:'p1',name:'プレイヤー1',residence:'',color:'p1'},{id:'p2',name:'プレイヤー2',residence:'',color:'p2'},{id:'p3',name:'プレイヤー3',residence:'',color:'p3'},{id:'p4',name:'プレイヤー4',residence:'',color:'p4'}],stays:[],settlements:[]};
let state=load();let route='map';let selectedPlayer=null;let selectedPref=null;let photoData='';
function load(){try{return {...structuredClone(DEFAULT),...JSON.parse(localStorage.getItem(KEY))}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function regionOf(code){return PREF[code]?.region}
function excludedCodes(){return new Set(state.players.map(p=>p.residence).filter(Boolean))}
function validStays(){return state.stays.filter(s=>s.valid!==false && state.game.started && s.date>=state.game.startDate && s.date<=today())}
function owners(){const ex=excludedCodes();const by={};PREFS.forEach(([c])=>{if(ex.has(c)){by[c]={type:'excluded'}}});const groups={};for(const s of validStays()){(groups[s.prefecture]??=[]).push(s)}for(const [code,list] of Object.entries(groups)){if(ex.has(code))continue;const dates=[...new Set(list.map(s=>s.date))];const max=dates.sort().at(-1);const same=list.filter(s=>s.date===max);by[code]=same.length>1?{type:'blank',date:max}:{type:'owned',playerId:same[0].playerId,date:max,stayId:same[0].id}}return by}
function currentPoints(){const o=owners();const ex=excludedCodes();const result=Object.fromEntries(state.players.map(p=>[p.id,0]));for(const [code,v] of Object.entries(o)){if(v.type!=='owned')continue;const p=state.players.find(x=>x.id===v.playerId);if(!p)continue;const base=regionOf(code)===regionOf(p.residence)?state.game.residencePoints:state.game.otherPoints;result[p.id]+=base}
return result}
function countOwned(pid){return Object.values(owners()).filter(v=>v.type==='owned'&&v.playerId===pid).length}
function playerColor(pid){return COLORS[state.players.find(p=>p.id===pid)?.color]||'#fffdf8'}
function render(){document.querySelector('#app').innerHTML=`<div class="app">${route==='map'?mapScreen():route==='record'?recordScreen():route==='history'?historyScreen():route==='setup'?setupScreen():route==='admin'?adminScreen():menuScreen()}</div>${nav()}`;if(route==='map')loadMap();}
function nav(){return `<nav class="bottom-nav">${[['map','🗾','マップ'],['record','📷','記録'],['history','▤','履歴'],['menu','☰','メニュー']].map(([r,i,t])=>`<button class="nav-btn ${route===r?'active':''}" onclick="go('${r}')"><span class="nav-icon">${i}</span>${t}</button>`).join('')}</nav>`}
function mapScreen(){const pts=currentPoints();return `<header class="topbar"><div><div class="eyebrow">TRAVEL TERRITORY</div><div class="title">日本全国陣取り</div><div class="period">第${state.game.period}期</div></div></header><section class="map-wrap"><div id="map">読み込み中…</div><div class="hokkaido-route"></div></section><div class="legend"><span>● 所有</span><span>■ 未取得</span><span>■ ブランク</span><span>■ 対象外</span><span style="margin-left:auto">対象 ${47-excludedCodes().size}県</span></div><section class="players">${state.players.map(p=>`<button class="player" onclick="showPlayer('${p.id}')"><span class="dot" style="background:${COLORS[p.color]}"></span><div class="player-main"><div class="player-name">${esc(p.name)}</div><div><span class="score">${pts[p.id]||0}pt</span><span class="count">${countOwned(p.id)}県</span></div></div></button>`).join('')}</section>`}
async function loadMap(){const el=document.querySelector('#map');try{const res=await fetch(MAP_URL);if(!res.ok)throw new Error();const text=await res.text();el.innerHTML=text;const svg=el.querySelector('svg');svg.setAttribute('aria-label','日本全国の都道府県地図');styleMap(svg);addLabels(svg);addRegionLines(svg);svg.querySelectorAll('.prefecture').forEach(g=>{g.addEventListener('click',()=>showPref(g.dataset.code));g.setAttribute('tabindex','0');g.setAttribute('role','button')});}catch{el.innerHTML='<div class="notice">地図データを読み込めませんでした。通信環境を確認してください。</div>'}}
function styleMap(svg){const o=owners();svg.querySelectorAll('.prefecture').forEach(g=>{const code=g.dataset.code;const v=o[code];let fill='#fffdf8';if(v?.type==='owned')fill=playerColor(v.playerId);if(v?.type==='blank')fill='#d8d8d8';if(v?.type==='excluded')fill='#8d8d8d';g.style.fill=fill;g.style.stroke='#8f887c';g.style.strokeWidth='1.3';if(v?.type==='owned')g.classList.add('owned')});}
function addLabels(svg){/* The source map already contains accessible prefecture titles; visual labels are kept within the map asset to avoid drifting outside tiny prefectures. */}
function addRegionLines(svg){
  const host=document.querySelector('.map-wrap');
  if(!host || host.querySelector('.region-overlay')) return;
  const wrap=document.createElement('div'); wrap.className='region-overlay';
  wrap.innerHTML=`<svg viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true">
    <path d="M735 170 L720 245 L695 305 L680 355"/>
    <path d="M665 345 L630 405 L600 470"/>
    <path d="M560 485 L535 525 L500 550"/>
    <path d="M455 565 L425 585 L385 605"/>
    <path d="M350 610 L320 635 L295 660"/>
    <path d="M405 705 L455 710 L505 700"/>
    <path d="M570 760 L620 780 L675 790"/>
  </svg>`;
  host.appendChild(wrap);
}
function showPref(code){selectedPref=code;const o=owners()[code]||{};const p=state.players.find(x=>x.id===o.playerId);openSheet(`<button class="sheet-close" onclick="closeSheet()">×</button><h2>${PREF[code].name}</h2><div class="row"><span class="label">状態</span><span class="value">${o.type==='excluded'?'対象外':o.type==='blank'?'ブランク':o.type==='owned'?`${esc(p?.name||'')}が所有`:'未取得'}</span></div>${o.date?`<div class="row"><span class="label">登録日</span><span class="value">${o.date}</span></div>`:''}`)}
function showPlayer(pid){selectedPlayer=pid;const p=state.players.find(x=>x.id===pid),pts=currentPoints();const list=PREFS.filter(([c])=>owners()[c]?.playerId===pid);openSheet(`<button class="sheet-close" onclick="closeSheet()">×</button><h2>${esc(p.name)}</h2><div class="row"><span class="label">期間ポイント</span><span class="value">${pts[pid]||0}pt</span></div><div class="row"><span class="label">所有県数</span><span class="value">${list.length}県</span></div><div class="row"><span class="label">居住県</span><span class="value">${PREF[p.residence]?.name||'未設定'}</span></div><h3>所有している都道府県</h3><div class="owner-list">${list.map(([c,n])=>`<span class="tag">${n}</span>`).join('')||'<span class="label">まだありません</span>'}</div>`)}
function recordScreen(){const photo=photoData?`<img class="preview" src="${photoData}" alt="証拠写真プレビュー">`:'';return `<h1 class="screen-title">旅行を記録</h1><p class="screen-sub">旅行した県を1件ずつ登録します。登録前に確認画面があります。</p>${!state.game.started?'<div class="notice">ゲーム開始後に記録を登録できます。</div>':''}<form class="form" onsubmit="event.preventDefault();goConfirm()"><div class="field"><label>プレイヤー</label><select id="r-player">${state.players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>都道府県</label><select id="r-pref">${PREFS.map(([c,n])=>`<option value="${c}" ${excludedCodes().has(c)?'disabled':''}>${n}${excludedCodes().has(c)?'（対象外）':''}</option>`).join('')}</select></div><div class="field"><label>滞在日</label><input id="r-date" type="date" max="${today()}" value="${today()}"></div><div class="field"><label>滞在種別</label><select id="r-type"><option>食事</option><option>観光</option><option>宿泊</option><option>旅行</option><option>その他</option></select></div><div class="field"><label>証拠写真1枚</label><div class="photo-box"><input id="r-photo" type="file" accept="image/*" onchange="readPhoto(event)">${photo}</div></div><div class="field"><label>コメント（任意）</label><textarea id="r-comment" placeholder="旅のメモなど"></textarea></div><button class="primary" type="submit" ${state.game.started?'':'disabled'}>登録の確認画面へ</button></form>`}
function readPhoto(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{photoData=r.result;render()};r.readAsDataURL(f)}
function goConfirm(){const data={playerId:document.querySelector('#r-player').value,prefecture:document.querySelector('#r-pref').value,date:document.querySelector('#r-date').value,type:document.querySelector('#r-type').value,comment:document.querySelector('#r-comment').value,photo:photoData};if(!data.date||data.date>today()||!data.photo){alert('滞在日と証拠写真1枚を入力してください。');return}openSheet(`<button class="sheet-close" onclick="closeSheet()">×</button><h2>登録内容の確認</h2><div class="confirm-card"><div class="row"><span class="label">プレイヤー</span><span class="value">${esc(state.players.find(p=>p.id===data.playerId)?.name)}</span></div><div class="row"><span class="label">都道府県</span><span class="value">${PREF[data.prefecture].name}</span></div><div class="row"><span class="label">滞在日</span><span class="value">${data.date}</span></div><div class="row"><span class="label">滞在種別</span><span class="value">${data.type}</span></div>${data.comment?`<div class="row"><span class="label">コメント</span><span class="value">${esc(data.comment)}</span></div>`:''}<img class="thumb" src="${data.photo}" alt="証拠写真"></div><div class="actions"><button class="secondary" onclick="closeSheet()">戻る</button><button class="primary" style="flex:1" onclick='saveStay(${JSON.stringify(data).replace(/'/g,"&#39;")})'>登録する</button></div>`)}
function saveStay(data){state.stays.push({id:crypto.randomUUID(),...data,createdAt:new Date().toISOString(),valid:true});save();photoData='';closeSheet();route='history';render();alert('旅行記録を登録しました。')}
function historyScreen(){const records=[...state.stays].sort((a,b)=>b.date.localeCompare(a.date));return `<h1 class="screen-title">履歴</h1><p class="screen-sub">登録した旅行記録。テスト中はここから削除できます。</p><div class="record-list">${records.length?records.map(r=>`<article class="record"><div class="record-head"><div><h3>${PREF[r.prefecture]?.name||r.prefecture}</h3><small>${esc(state.players.find(p=>p.id===r.playerId)?.name||'')} ・ ${r.date} ・ ${r.type}</small></div><button class="danger" onclick="deleteStay('${r.id}')">削除</button></div>${r.comment?`<p>${esc(r.comment)}</p>`:''}${r.photo?`<img src="${r.photo}" alt="証拠写真">`:''}</article>`).join(''):'<div class="empty">まだ旅行記録がありません。</div>'}</div>`}
function deleteStay(id){if(!confirm('このテスト用旅行記録を削除しますか？'))return;state.stays=state.stays.filter(s=>s.id!==id);save();render()}
function setupScreen(){return `<h1 class="screen-title">プレイヤー登録</h1><p class="screen-sub">4人の名前・現在の居住県・色を設定してゲームを開始します。</p><div class="setup-grid">${state.players.map((p,i)=>`<div class="player-setup"><input id="pn-${i}" value="${esc(p.name)}" placeholder="プレイヤー${i+1}"><select id="pr-${i}"><option value="">居住県を選択</option>${PREFS.map(([c,n])=>`<option value="${c}" ${p.residence===c?'selected':''}>${n}</option>`).join('')}</select><select class="color-select" id="pc-${i}">${Object.entries(COLORS).map(([k,c])=>`<option value="${k}" ${p.color===k?'selected':''}>●</option>`).join('')}</select></div>`).join('')}</div><button class="primary" style="margin-top:18px" onclick="startGame()">この4人でゲームを開始</button>`}
function startGame(){const colors=[];for(let i=0;i<4;i++){const name=document.querySelector('#pn-'+i).value.trim()||`プレイヤー${i+1}`,res=document.querySelector('#pr-'+i).value,col=document.querySelector('#pc-'+i).value;if(!res){alert('4人の居住県を設定してください。');return}if(colors.includes(col)){alert('プレイヤーカラーは重複できません。');return}colors.push(col);state.players[i]={...state.players[i],name,residence:res,color:col}}state.game.started=true;state.game.startDate=state.game.startDate||today();save();route='map';render()}
function menuScreen(){return `<h1 class="screen-title">メニュー</h1><p class="screen-sub">ゲームの管理と登録をここから行います。</p><div class="menu-list"><button class="menu-item" onclick="route='setup';render()">プレイヤー登録・変更 <span>›</span></button><button class="menu-item" onclick="route='admin';render()">管理者ページ <span>›</span></button><button class="menu-item" onclick="resetDemo()">テストデータを初期化 <span>›</span></button></div>`}
function adminScreen(){const pts=currentPoints();return `<h1 class="screen-title">管理者ページ</h1><p class="screen-sub">認証なしのMVP管理画面。公開前にSupabase RLS等を設定してください。</p><div class="admin-grid"><div class="metric">ゲーム状態<br><strong>${state.game.started?'進行中':'未開始'}</strong></div><div class="metric">開始日<br><strong>${state.game.startDate||'—'}</strong></div><div class="metric">居住地方ポイント / その他<br><strong>${state.game.residencePoints} / ${state.game.otherPoints} pt</strong></div><div class="panel"><h3>ポイント設定</h3><div class="row"><span>居住地方</span><input id="resPts" type="number" value="${state.game.residencePoints}" style="width:90px"></div><div class="row"><span>その他地方</span><input id="otherPts" type="number" value="${state.game.otherPoints}" style="width:90px"></div><button class="secondary" onclick="saveSettings()">保存</button></div><div class="panel"><h3>決着</h3><p class="screen-sub">地図と累積ポイントは維持し、期間ポイントの起点を記録します。</p><button class="primary" onclick="settle()">現在の状態で決着する</button></div></div>`}
function saveSettings(){state.game.residencePoints=Number(document.querySelector('#resPts').value)||5;state.game.otherPoints=Number(document.querySelector('#otherPts').value)||10;save();render()}
function settle(){const pts=currentPoints();state.settlements.push({id:crypto.randomUUID(),at:new Date().toISOString(),points:pts,players:state.players.map(p=>({id:p.id,name:p.name,cumulative:pts[p.id]||0}))});state.game.period+=1;save();render();alert('決着を記録しました。')}
function resetDemo(){if(!confirm('すべてのテストデータを初期化しますか？'))return;state=structuredClone(DEFAULT);save();route='setup';render()}
function openSheet(html){let old=document.querySelector('.modal-back');if(old)old.remove();const d=document.createElement('div');d.className='modal-back';d.innerHTML=`<section class="sheet">${html}</section>`;d.addEventListener('click',e=>{if(e.target===d)closeSheet()});document.body.appendChild(d)}function closeSheet(){document.querySelector('.modal-back')?.remove()}
window.go=(r)=>{route=r;render()};window.showPlayer=showPlayer;window.showPref=showPref;window.closeSheet=closeSheet;window.readPhoto=readPhoto;window.goConfirm=goConfirm;window.saveStay=saveStay;window.deleteStay=deleteStay;window.startGame=startGame;window.saveSettings=saveSettings;window.settle=settle;window.resetDemo=resetDemo;
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
